/// Generated by expo-google-fonts/generator
/// Do not edit by hand unless you know what you are doing
///
  

export { useFonts } from './useFonts';

export const __metadata__: Any;
export const SF_Pro_Text_Ultralight: number;
export const SF_Pro_Display_Bold: number;   
export const SF_Pro_Display_Black: number;
export const SF_Pro_Display_Medium: number;
export const SF_Pro_Rounded_Black: number;
export const SF_Pro_Rounded_Medium: number;
export const SF_Pro_Text_Black: number;
export const SF_Pro_Text_Bold: number;
export const SF_Pro_Text_Heavy: number;
export const SF_Pro_Text_Light: number;
export const SF_Pro_Text_LightItalic: number; 
export const SF_Pro_Text_Medium: number; 
export const SF_Pro_Text_Regular: number; 
export const SF_Pro_Text_Thin: number;
